### PR TITLE
Added -d to UMLET_HOME detection

### PR DESCRIPTION
**Pull request by BenTyger**
Added -d to UMLET_HOME override detection

### CODE REVIEW

**Comment by afdia** [comment]
Hi, what would be the effect of/reason for this change?

**Comment by keesj** [comment]
man test shows:
```
       -d FILE
              FILE exists and is a directory
```

Hence this patch verifies that the given UMLET_HOME is a directory and else (silently) ignores it. To me it looks like an attempt at doing more validation but in such cases I would argue it it better to show a warning or let the script fail (so somebody can see what is wrong) v.s. ignoring the variable.

**Comment by afdia** [comment]
Thanks for your comment.
If this was the idea, I agree that a UMLET_HOME var which does not point to a directory should not be ignored but remain an error (the user can then remove or fix the value)

(I leave it open for some time to hear from the author, maybe there is another idea behind this change)

**Comment by afdia** [comment]
I have tried the current script which says the following if UMLET_HOME=/mnt/dir/testfile.txt (which is a file and not a dir):
`Error: Unable to access jarfile /mnt/dir/testfile.txt/umlet.jar`

If i merge this pull request it gets silently ignored instead

I prefer the error, but I have added a simple check to make sure it points to a directory if it's used.

**Pull request closed without merging**
