### PR TITLE
Eclipse integration

### PR DESCRIPTION
**Pull request by ruediste**
Implements #346 without (7). Remark: To enable the new features, right-click on a Java project -> Configure -> enable Umlet Builder

### CODE REVIEW

**Comment by afdia** [comment]
thanks, I dont have much time at the moment, but I will check it out and merge it in the next week

**Comment by afdia** [comment]
Hi
I've checked out your branch but couldn't get the image links or the builder to work.

Although the project compiles and the Eclipse Plugin Debug launcher works, it looks like the old UMLet plugin and none of the new features are usable.

My test project has a src dir with a test package which contains the class:
`/**  */
public class Test {}`
The Test.uxf is in the same directory.

If I use Properties -> Builders -> New it doesnt suggest to add a Umlet/UXF builder.

I use Eclipse for RCP and RAP Developers 4.5.1 (Build id: 20150924-1200)
I guess it's the OOMPH Eclipse Installer version if that matters

Do you have any idea why it doesnt work for me?

**Comment by afdia** [comment]
Ok some feedback about the enumeration in issue #346:

About 1 Builder: Automatically export all .uxf diagrams to .png:
After enabling the Umlet builder, it automatically generates the pngs next to the uxf files which is really nice.

There is one thing I am sure of, however: Is it correct that the pngs are located in the same directory as the uxf files or should they be generated into the build-directory of the project (bin or target)?
Especially if we think about a maven plugin which also generates sources, it should probably generate them into the target dir instead of the src dir.

It's not a major concern though and I guess the current implementation is OK if it's easier for the rest of the features to work, but in general the user should probably never see the pngs in his workspace (because he is working with the uxf files)
What do you think?

Another minor bug is: if I change the uxf file, save and close it, the png will not be regenerated (and therefore the image links will show the old version) until I trigger a project build manually.
It would be nice if saving the uxf would trigger the builder for this uxf file.
____________
About 2 Content assist for linking to existing diagrams from JavaDocs (insert  tags):
Nice feature, but it should only suggest pngs which are generated by the Umlet Builder (or perhaps pngs where a uxf file exists), otherwise any pngs can be linked which is probably not what the user expects from an Umlet plugin.

The only possible issue is that it always suggests all uxf diagrams and this list could grow very large for large projects, but I guess for most projects there should not exist hundreds of uxf files.

One nice additional feature would be:
If there exists a Plots.uxf and the user intends to link it, he will probably type "pl" -> Ctrl+Space. Currently this does not suggest `Link to Plots.png` although it probably should (technically this should take all link suggestions and filter the file name with the portion the user typed in)
____________
About 3 Switch between absolute and relative image links:
I guess this is the "press ctrl+space while cursor is on an image link" -> "Transform xxx to yyy" feature?
I like it!
One minor issue is that if I have an entry `` it suggests `Change link to Plots.png` above the transform sugestion, which doesnt do anything. I guess this suggestion should be removed.
____________
About 4 add hyperlink to navigate from  tags to the corresponding .uxf diagram:
Simple and useful, I like it!
____________
About 5 Move and Rename participants to keep  refs stable:
Very nice and useful feature (otherwise javadocs would probably often break)

One minor problem is linked to `About 1 ...`:
Because the png is generated into the same dir, the user can also rename the png which will not work.
If the generated pngs would be located in the bin or target dir, the user would not even see them and could not make this mistake.
____________
About 6 option to create a new umlet diagram in doc-files as content assist:
I'm not sure if the JavaDoc is the right location to create new uxf files, but it is a nice shortcut for users who want to use the JavaDoc integration, therefore I think it's fine.

There are 2 problems with the current implementation:
1. `Link to new image ...` should be called `Create and link Umlet diagram ...` to make clear what will happen
2. it should not work on an empty line because filenames must be longer than 0 chars.

There is also a problem with the zero length suggestion - e.g. if I have the following class:
> /** CURSOR_POS
 */
public class Test {}

and my cursor is at CURSOR_POS and I press ctrl+space it will cause an error and break the package linke before.
Therefore suggest the "create and link" only if the user has typed in some characters.
____________

In general I really like the builder and javadoc integration!

**Comment by ruediste** [comment]
1) I would also like to separate the pngs from the uxfs, but eclipse only displays images in the same source folder as the source file itself. So I think keeping them in the same place is the thing to do.

I just recognized the image search looks in all source folders. I'll fix that. Same for the refactorings.

Saving the uxf should trigger the png regeneration. Be aware that the javadoc view is not updated when the image changes (that's how eclipse works). I've also seen issues with the regeneration on windows. Currently the regeneration works directly on the file system. I guess the eclipse way of accessing resources should be used. This will require a minor refactoring of the umlet export to support streams.

2) Fair point about the scope of the umlet plugin. I'll change that to search for uxf files and link to the corresponding pngs.

additional feature: I guess you mean case insensitive search. I like

3) minor issue: good point

5) I will try to rename the uxf along with the png, if the png is renamed.

6) 
  1) better text: good point 
  2) according to the [javadoc documentation](http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html#images), the doc-files subfolder is the right place. Agree?
  3) only when the user typed characters: correct. What about a min of 3 characters?

final question: yes that's right, the features are only available if the user adds the umlet builder (which adds the umlet nature, which is what enables the new features)

**Comment by afdia** [comment]
1) I agree, keep the images in the same folder. Otherwise it is a potential source of errors and if one is using the Maven directory structure (https://maven.apache.org/plugins/maven-javadoc-plugin/examples/javadoc-resources.html), the javadoc files are separated anyways and I guess it's OK if the uxfs and the pngs are located there

2) Yes I mean a case insensitive search

6.2) Didn't know about that, but in that case I agree
6.3) Perhaps 3 chars appear to arbitrary to the user, so I would stick with 1 char (it's the minimum amount required by the filesystem) or do you see a potential conflict with other suggestions/eclipse features if it only requires 1 char?

**Comment by ruediste** [comment]
6.3) 1 char is fine with me.

General: Thanks for the feedback, I'll see when I come to fix the issues.

**Comment by ruediste** [comment]
OK, issues should be fixed now

**Comment by afdia** [comment]
Thanks, I will check it out in the next few days and merge it if everything is fine.
We will release 14.2 without this feature (because we're already preparing the release) but it will most likely be part of 14.3

**Comment by afdia** [comment]
Sorry for the delay.
I've tried it out and most problems are fixed.

Remaining issues are:
- If my cursor is right next to the `/**` part of the JavaDocs first line and I press ctrl+space it suggests to create and links a diagram which breaks the class (see issue described before with CURSOR_POS)
- If I rename the png, the uxf and Javadoc will not be renamed, the other way works (renaming uxf renames png and javadoc)

Other than that we should probably write a short information for users to let them know about these new features.
I have written a first version, perhaps you can check if I have forgotten anything:

- Enable improved Eclipse integration with **Right click > configure > Enable Umlet Builder** to get the following features:
- After saving an uxf file, Eclipse automatically exports a png file next to it.
- Renaming an uxf file will automatically rename the exported png and every JavaDoc link
- Link UMLet diagrams in Javadoc using ``
	- There is content assist for it, if you press ctrl+space multiple times until "Link to diagram.png" shows up
	- type part of the diagram name and content assist will only suggest diagrams with a name matching this partial string
	- click on an existing diagram path in Javadoc press ctrl+space to switch to a path relative to {@docRoot}
	- ctrl+click on an existing diagram path in Javadoc opens the diagram uxf in an Eclipse tab
	- type a diagram name while within a JavaDoc block and press Ctrl+Space until "Create and link new Umlet diagram ..." shows up to automatically create a uxf file with the suggested name

**Comment by ruediste** [comment]
Hello,

I've just solved the two issues you mentioned. Sorry for having overlooked then when going thought the issue list before.

Regarding the user information, I think you pretty much covered it. However, I would change the "file rename" part to:

- The image links in the JavaDocs are updated when moving classes, packages, files and directories as well as when renaming image files.

**Comment by afdia** [comment]
Thanks, I have checked it and the 2 issues are fixed.
Have you found anything else or should I merge the pull request?

**Comment by ruediste** [comment]
Hello Andreas,

No, no open issues from my side. Ready to merge. :-)

Regards

**Pull request merged**
