### PR TITLE
Merge VSCode changes Pt6 (UVC-032)

### PR DESCRIPTION
**Pull request by e01306821**
see #585

This PR also includes the following non-tracked fix:

- Improved responsiveness of the download UI for Umletino

### CODE REVIEW

**Comment by afdia** [comment]
I have tested it in umletino and the basics work, but if I copy&paste elements between diagrams with different zoom levels it resizes the elements:
* e.g copy from palette at 80% to diagram at 100%
* copy diagram element at 100%, zoom to 20%, paste
* copy from a tab with diagram at 100% and insert into another tab into a diagram at 50%

Zoom and copy&paste also caused similar issues with swing umlet so perhaps take a look at the code there maybe you can fix it in a similar way.
E.g. the class ClipBoard.java shows  that elements are zoomed to 100% before remembering them within the clipboard and are zoomed to the zoomlevel of the diagram they should be pasted into.
Maybe a similar solution can fix this problem

**Comment by e01306821** [comment]
Sorry, I completely forgot to test copy/paste mechanics after implementing these changes. After further testing I also encountered additional issues that should now be fixed as well. Thank you for testing!

**Comment by e01306821** [comment]
I've now fixed all encountered issues

**Comment by afdia** [comment]
Thanks now it looks good!

**Pull request merged**
