### PR TITLE
fix GWT compile errors

### PR DESCRIPTION
**Pull request by ruediste**
I tried to run Umletino and had to fix some GWT compile errors. Deque was not supported, as well as some copy operations on Arrays.

### CODE REVIEW

**Comment by afdia** [comment]
Hi

Which version of GWT are you using and what do you do to provoke those errors?
I've just tried it on my PC with GWT 2.7.0 and it works.

Perhaps you use GWT 2.6.0 where at least Arrays.copyOf is possibly not emulated (see https://code.google.com/p/google-web-toolkit/issues/detail?id=8473 which mentions it works since GWT 2.7.0 RC1)

**Comment by ruediste** [comment]
You are right, I'm on 2.6.0.

**Comment by afdia** [comment]
Can you check if the origin/master works with GWT 2.7.0 (it should) and if it works I would close this pull request.
But I will mention this in the wiki developer FAQ to make sure it's clear that 2.7.0 is the minimum version.

**Comment by ruediste** [comment]
Updated to 2.7.0 and everything works fine.

**Pull request closed without merging**
