### PR TITLE
Umlet unix wrapper: Allow to symlink the umtlet.sh

### PR DESCRIPTION
**Pull request by keesj**
The default umlet.sh script is using a trick to resolve the default umlet path but this trick is not working well when using symbolic links. In this patch realink is used to resolve the path of the shell script instead of $0 directly

With this change in in place I was able to test that creating a symbolic link from a bin directory to the umlet.sh wrapper now works nicely but the old behaviour: adding umlet.sh into the path is also still functional.

Tested on Ubuntu 22.04 with UMLet version 15.1 2023-03-12

### CODE REVIEW

**Comment by keesj** [comment]
This patch achieves the same as  #653 but is POSIX compliant

**Comment by afdia** [comment]
Hi thanks for the suggestion, but I have tried it with a dir name which contains spaces (because they are often problematic and therefore a good test case) and this change will break the script.

the following show the difference if executed from a dir like /mnt/temp/1 2 3/
```
_UMLET_HOME="$(cd $(dirname $0);pwd)"
echo $_UMLET_HOME
```
prints /mnt/temp/1 2 3

```
_UMLET_HOME="$(dirname $(readlink -f $0))"
echo $_UMLET_HOME
```
prints /mnt/temp . 3

The other pull request has the same issue. If you can fix the issue I will merge this pull request :)

**Comment by keesj** [comment]
@afdia I added support for space in the second version of the code. It did require making small changes in the rest of the script. but it all now works4me. The construct is interesting because the inner quotes around $0 do not need to be escaped, I learned something new today

**Comment by afdia** [comment]
Thanks for the update, my test worked too and it looks good :)

**Pull request merged**
