### PR TITLE
Migrate Build to Maven

### PR DESCRIPTION
**Pull request by ruediste**
I started the maven migration. EclipsePlugin and Standalone should work (both from eclipse and the built artefacts). I added a short description of the modules to the Readme. Please review. Is this the way to go? What do you think? I did not touch the GWT project yet.

### CODE REVIEW

**Comment by afdia** [comment]
Hi
Thanks for your effort, it's really not an easy task to "mavenize" the projects.

One important thing before going into detail:
I'm thinking about how this migration should work out in terms of versioning. I'm not really happy to apply a huge pull request which changes everything at once.

What do you think about the following procedure:
1. I change the directory structure in advance (src dir to src/main/java, test to test/main/java)
2. I change the folder names after they are final (see comments below)
Afterwards you rebase your branch on these changes and the overall amount of stuff which moves by this pull should be much lower (only pom.xml files and the extraction of the eclipse and standalone specific stuff)
What do you think?

Now to the content:
I've only skimmed through it and have some comments/questions (I guess it's easier to make a list here instead of commenting the files because of the huge amount of move-commands):

1. Please drop the name baselet (it is only used for legacy reasons because there was a spin off project called Plotlet, but it has been retired and the Plots palette is now part of umlet)
Therefore instead of umlet-baselet-* it should only be umlet-*

2. I needed to add the dependency
		<dependency>
			<groupId>com.github.ruediste.umlet</groupId>
			<artifactId>umlet-baselet-res</artifactId>
			<version>${project.version}</version>
		</dependency>
to umlet-baselet, otherwise the dependency-plugin would search umlet-baselet-res in the remote repository and not in the local dependency

3. After the mentioned change, I can mvn install the umlet-parent project, but the com.umlet.plugin project shows errors in eclipse, because it doesn't find UMLets dependencies (batik libraries, itextpdf, ...)
If I Alt+F5 in Eclipse (refresh project from pom.xml), I get the error "Resource '/BaseletElements' does not exist"
Perhaps some configuration is wrong/missing?

4. I would also change the names of the directories to match their artifactId. If we make such a huge change to all files we should also unify this, I guess

5. @umlet-parent: maven-compiler-plugin
version should be 1.6 (currently we support Java6+)

Is there a reason why you don't use the following maven properties (instead of configuring the compiler-plugin):
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.6</maven.compiler.source>
    <maven.compiler.target>1.6</maven.compiler.target>
</properties>

6. Is there a reason for extracting the dependencies of the projects into separate "-deps" modules? If not, I think it would be better and easier to understand if they are just mentioned in the appropriate module (perhaps this would also fix point 3 of this list)

I would also include the content of umlet-baselet-res directly in umlet-baselet if possible.

7. One more thing about project names: umlet-baselet should probably be renamed to umlet-baselet-swing (or umlet-swing after applying point 1 of this list) to make it clear that it's the swing related part which is shared by the plugin and standalone umlet and that it has nothing to do with umlet-gwt (UMLetino)


Other than that it looks really nice!
If everything works after the maven migration, I guess I will merge it because it solves many fragile parts of UMLet (like calling JavaCC manually after checkout, running tests manually, src-dir vs project dependencies as mentioned in the wiki, ...)


TODO after the migration (just for documentation):
1. the package and version should be changed (I would call the groupId com.umlet and the version whatever the next release version will be)

**Comment by ruediste** [comment]
Sorry for replying this late, I'm quite busy in the moment. 6 weeks old daughter...

I looked at your points and agree more ore less everywhere, especially in the versioning part. I just wanted to get the overall concepts working without worriying about it and get some feedback as soon as possible.

I hope to come back to this next weekend or the week afterwards. Three weeks of vacations ahead :-)

**Comment by afdia** [comment]
No problem, take your time, we're not in a hurry :)
We're happy to take contributions and this is a tough one.

Just for your info: we're currently planning the next UMLet release (perhaps slightly delayed due to vacations), afterwards I plan to do some preparations for this migration (renaming the projects and moving the files to the maven structure)
This would avoid many changes/file moves of this pull request and therefore it should require (almost?) no merge an could easily stay up to day for several month and can be developed in parallel to most other features which will only touch the java classes.

Therefore take your time and have a nice christmas :)

**Comment by ruediste** [comment]
I found some time to work on this again. I solved all issues you mentioned except the custom element one. However, I did the reorganization myself (in one go). Next points on my agenda:

1. make sure the assemblies are correct (I think I've seen some spurious lib files)
1. get GWT running
1. test all the various ways of launching again

**Comment by afdia** [comment]
Thanks it looks much better with the renames!

As soon as I find some time, I will check out the projects and can give some more feedback, but 2 minor things I've seen in the browser compare of c4503d9d19dcef360e85a2b675700f52eea33acb are:
1. The formatting of some files has changed, which makes some comments look very ugly (e.g. https://github.com/ruediste/umlet/blob/c4503d9d19dcef360e85a2b675700f52eea33acb/umlet-swing/src/main/java/com/baselet/diagram/StartUpHelpText.java). I guess it's because you used the default 80char limit of Eclipse.

2. If it's not too complicated, it would be nice if the java files which have moved to separate projects would also be shown as a "rename" and not as unrelated deletes/adds. This would make the real changes due to the maven migration better visible and unexpected changes like the formating would be easier to see.

One hint for the GWT migration: if you find some problems with the mojo gwt plugin (which I used in the maven branch) perhaps try out the alternative one from tbroyer (he seems to be very active on gwt related quiestions on stackoverflow and the gwt related groups): https://github.com/tbroyer/gwt-maven-plugin

**Comment by ruediste** [comment]
Formatting issues: I usually use auto formatting when I'm developing. I
switched that off now, undid the formatting changes and extracted the real
changes into separate commits.

GWT: thanks a lot for the hint. Might me save ours later.

**Comment by afdia** [comment]
Currently the Baselet projects have project specific formatter settings (mostly the default but without line width limit) and also enable autoformatting.
e.g. https://github.com/umlet/umlet/blob/master/Baselet/.settings/org.eclipse.jdt.core.prefs

I have checked your branch and it seems that they are currently missing. If you use them for your new projects, you shouldn't need to change your local Eclipse settings :)

**Comment by ruediste** [comment]
Ok, I think I'm more or less done. I tried to get the GWT build running, but gave up after an evening or two. 

In addition I did setup a travis build, see https://travis-ci.org/ruediste/umlet. The snapshot builds are pushed to the sonatype repository. To use, add

```
<repository>
    <id>sonatype.snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

to your `pom.xml`. Furthermore, I configured an upload of the plugin and the standalone distribution to S3. Download URLS are:

https://s3.eu-central-1.amazonaws.com/umlet.ruediste.github.com/umlet-standalone-14.1.0-SNAPSHOT.zip
https://s3.eu-central-1.amazonaws.com/umlet.ruediste.github.com/umlet-standalone-14.1.0-SNAPSHOT.tar.bz2
https://s3.eu-central-1.amazonaws.com/umlet.ruediste.github.com/com.umlet.plugin-14.1.0-SNAPSHOT.jar

A directory listing can be retrieved from

https://s3.eu-central-1.amazonaws.com/umlet.ruediste.github.com/

I've seen that maven central contains a single upload of umlet under the com.umlet group id. Do you own that ID? How should we organize the building and uploading? Should I setup the CI-Build? What do you think?

**Comment by afdia** [comment]
Hi
I have created a separate branch to help you with the maven migration: https://github.com/umlet/umlet/tree/maven

There I've successfully set up the gwt project (please check if it works for you too). The missing part is migrating the content of the antfile to maven (zipping the output and putting the versioninfo into a properties file which is read during runtime)

I can build the whole project, but I still have some Eclipse errors in the umlet-plugin project:
Project 'com.umlet.plugin' is missing required source folder: '/umlet-elements/src/main/java'
Project 'com.umlet.plugin' is missing required source folder: '/umlet-swing/src/main/java'

**Comment by afdia** [comment]
I've done some additional work which means that the gwt part should be finished.
The only remaining issue is that I still need 2 jars because one of them is not available in a maven repo and the GWT Eclipse Plugin SuperDev launcher doesnt find them if they are only available as maven dependencies.

I would suggest to close this pull request (because it has been merged to the new branch) and work on the remaining issues in separate pull requests which target the migration-branch?

The next important step would be fixing the source folder issues in the eclipse plugin and perhaps changing to the pom-first variant if possible; what do you think?

**Comment by ruediste** [comment]
Great work on the GWT project :-) 

I fixed the error with the plugin project. Creating a pull request. Still think anything needs to be changed with the plugin?

questions:

1. the name of the plugin (MANIFEST.MF) has to match the name of the pom artifact. Renaming all artifacts: not that maven like. I'd stick with the current setup...
2. I copy all dependencies transitively. This can only be achieved with a `copy-dependencies`. Since the tycho plugin adds the eclipse dependencies to the plugin project, doing the copying in the plugin project would also copy the eclipse deps. That's why its in a separate project.
3. The resources are copied by the maven build to the directory of the eclipse plugin. Again, keeping it in a separate project and using `unpack` makes this easy.

Additional work:

1. I did already setup some travis builds before, but it's quite simple (and you already have the config)
2. I already switched from S3 to github publishing. The Idea was to publish the latest CI builds, so users could always use the bleeding edge. It was never intended as replacement for release builds.
3. The ID registration works by contacting the sonatype team via a Jira issue. As far as I understand the policies, it should be quite easy to convince them to pass you the authority of the com.umlet group id if you present them your case.

I'm closing the pull request now. Don't hesitate to get in touch with me for the CI-Build or MavenCentral stuff.

**Comment by afdia** [comment]
sorry I overlooked the last comment.
I've tried some time to reduce the modules and the deps module seems to be necessary.
Perhaps the res module can be split up and moved to the appropriate modules though, I will give it a try in the next days/weeks

About add work 2: I will suggest it to the team, but I guess the main concern is that if it gets too easy to get nightly/snapshot builds, even non-developers can download them, use them and perhaps report non-errors which could potentially make support in general a bit more difficult. We will think about it.

I've also created an issue for the remaining parts of the migration #338

**Pull request closed without merging**
