### PR TITLE
Erd arrow endings

### PR DESCRIPTION
**Pull request by paulsmithkc**
Adding support for ERD style arrow endings.

### CODE REVIEW

**Comment by afdia** [comment]
Thanks for the contribution. I have made some changes and pushed a new branch https://github.com/umlet/umlet/tree/pr/551

Changes:
- removed unrelated commits about gitignore and source/target (especially because this would update the min java version without any need)
- removed the duplicated SINGLE_HASH and DOUBLE_HASH arrow ends (I guess they are leftovers from previous tries?). They caused umlets autocompletion to show | and || as valid arrow ends when they were not (because the escaping of the regex was missing)
- changed 1 to | and 0 to o. The first change is because we already use | to make a vertical line so it would be unexpected to use 1 instead. The second change is made because "o" looks more like a small circle and it is visual distinct from the large O and the zero 0. Otherwise some fonts would make zero and O look very similar and it could be hard to find the correct sign
- added some constants for the radius of the circle

You can view the commit in the branch https://github.com/umlet/umlet/tree/pr/551 and let me know if you think that I have introduced an error or if you see a problem with the changes.
If it looks fine to you, I will merge the pr/551 branch and close this one, or if you prefer you can change this pull request accordingly and I will merge it.

Thanks!

**Comment by paulsmithkc** [comment]
Looks good. I don't see problems with your changes. 

Thank you for the fast response.

**Comment by afdia** [comment]
I've merged the changes it will be part of the next release, thanks again for the contribution

**Comment by paulsmithkc** [comment]
@afdia  Any word on when this will make it into a release?

**Comment by afdia** [comment]
They will be part of the next release, the question is just when it will be done. We're currently working on 2 major things (vscode plugin and new js-based custom elements) which take a bit more time than we planned.

I hope it will be in the next few weeks when those 2 features are stable/finished.

**Comment by jerrywoo96** [comment]
i tried `lt=-o|`, i cannot get the 0..1 relation.
image

image

**Comment by afdia** [comment]
The new arrow ends are shown in the screenshot above:
grafik

As you can see, unfortunately there is no lt=-o| (both endings are possible but not the combination)

**Comment by jerrywoo96** [comment]
> The new arrow ends are shown in the screenshot above: grafik
> 
> As you can see, unfortunately there is no lt=-o| (both endings are possible but not the combination)

@afdia 

so is the 0..1 ending going to be implemented? 🤔

**Comment by afdia** [comment]
We try to add missing UML elements and features in the future, but currently we are not working on it

**Comment by paulsmithkc** [comment]
I see that you finally released it on version 15. 🎉  I just wish this hadn't taken 3 years. 😢

**Comment by Mighty8086** [comment]
@paulsmithkc Sorry for the primitive question: I am using version 15 right now, but can't find the Crow's notation elements anywhere. Neither in umletino nor in the desktop build of 15.0.0. I see the commit, but where is it in the UI? Is it part of a custom elements libraray?

**Comment by paulsmithkc** [comment]
Add a line/connector to your diagram and then change the line endings in the property panel.

**Pull request closed without merging**
