### PR TITLE
Show type of element selection

### PR DESCRIPTION
**Pull request by schuellerf**
I sometimes have the problem that I see a "box" and it has different properties.
So I tried to show this in the heading of the "Properties" box...

Here are some examples where you see two boxes and when you select them you see that they are not the same. One is a class while the other is a "UMLGeneric" 

noselection
umlclass
umlgeneric

And I didn't find out up to now why the iterators have problems with (I think) pre-allocated ArrayList items in my setup (referring to c565fe8)

### CODE REVIEW

**Comment by afdia** [comment]
Hi
This feature already exists. You have to enable the developer options which shows some more information about the elements including the element name
It shows the name on the bottom right of selected elements, so you can check more types at once.

Perhaps we could extract this option from the "developer options" into a separate option, because it's probably useful for more people than only developers.
But in general we try to keep the basic program simple for most users and only enable advanced features if the user wants to see them.

**Comment by schuellerf** [comment]
Yes, you got it - I didn't see this option before :)

**Comment by barthel** [comment]
@schuellerf Does the developer option do what you want?
@afdia Do you want this feature?

Personally, the developer information is sufficient for me.

**Comment by afdia** [comment]
I would keep it as it is; the developer mode option already says that it shows extended element info and many users who just want to quickly draw diagrams don't need this extended info (they probably just use elements from the palettes for fitting use cases without knowing the technical details)

**Comment by barthel** [comment]
@afdia That's fine. Could this PR be closed then?

**Pull request closed without merging**
