### PR TITLE
Issue 520 hot key have no effect in eclipse on linux

### PR DESCRIPTION
**Pull request by ddetleffsen**
### Fixed: 

Hot keys 
- ^C Copy
- ^X Cut
- ^V Paste
- ^A Select All
- ^S Save
- DEL Delete

work in diagram, palette and property panels. 

tested on Linux Ubuntu 16.04, Java 8 and 11, eclipse photon plugin

### Open issues:

The hot keys 
- ^G Group
- ^U Ungroup

are recognized, but the action has no effect.

Sometimes the Tab that contains the diagram editor does not receive focus, if you click into the diagramm from a SWT control. In this case you have to click onto the tab to select it. Otherwise the hot keys have no effect.

### Proposal:
In my opinion the actions Cut, Paste, Delete make no sense in the palette panel. I would ignore them.

### Remark:
This fix is a workaround. The origin of the problem lies in the SWT AWT integration. The AWT event thread swallows the KeyEvents without notifying the SWT event processing. Therefore the eclipse KeyBindingDispatcher, that is responsible for executing the actions, is not called. This bug is platform dependend, therefore the fix is only activated for platform 'gtk'

### CODE REVIEW

**Comment by afdia** [comment]
Thanks again for your contributions!

I'm ok with a workaround if we cannot fix the underlying issue.

About your proposal: You're right that only Copy really makes sense, but to be consistent with the other platforms I would not dissalow the usage of Cut, Paste, Delete.
I don't remember complaints about unintentional removal of elements in the palette and perhaps some people want to temporarily change their palette for the current work session so perhaps there is some use of these commands for some people, so I tend to not disallow them as long as nobody complains.

**Comment by ddetleffsen** [comment]
The update of MANIFEST.MF is required to define the dependencies of the OSGi bundles in eclipse. To access the eclise KeyBindingDispatcher we need the dependencies to the plugins (bundles) org.eclipse.e4.core.context and org.eclipse.e4.ui.bindings. Otherwise you will have compile errors in the eclipse IDE and you are not able to install the plugin.

The maven build uses tycho and tycho is configured to update in the manifest file the classpath property only. I tested the maven goals clean, verify and install. No problem with the manifest.

**Comment by ddetleffsen** [comment]
The umlet application has the menu entry 'Edit Current Palette', that opens the palette as a diagram. That should be the place, where to change a palette.

**Comment by ddetleffsen** [comment]
Nice that you fixed the Java 11 problem.

**Comment by ddetleffsen** [comment]
As soon as you merged and tested my hotkey fix, everything I am interested in, is fixed and I would go back to work ;-) and drop my fork.

For me it was just a little training.

Just one proposal. I would set the default value for transparency to 0, at least for compact elements like classes.

**Comment by afdia** [comment]
I have merged both pull requests, built the plugin and it seems to work, so thanks again for the contribution!

One last thing about this pull request:
Eclipse complains about `The type org.eclipse.e4.ui.workbench.IWorkbench cannot be resolved. It is indirectly referenced from required .class files`, so I have added `org.eclipse.e4.ui.workbench` to the manifest to make it work. It worked with and without this addition, but I guess it's still a correct addition to let Eclipse know which parts the plugin is using

Eclipse also complains about using internal apis:
* `Discouraged access: The type 'KeyBindingDispatcher' is not API (restriction on required library 'C:\Users\Dia\.p2neon\pool\plugins\org.eclipse.e4.ui.bindings_0.12.300.v20180913-1535.jar')`
* `Discouraged access: The type 'Workbench' is not API (restriction on required library 'C:\Users\Dia\.p2neon\pool\plugins\org.eclipse.ui.workbench_3.112.100.v20181030-1443.jar')`

Do you know of any public apis which can be used instead to avoid these warnings?
I have found the interface IWorkspace which can be retrieved via `ResourcesPlugin.getWorkspace()` (see https://stackoverflow.com/questions/23691464/how-to-get-workspace-path-in-eclipse/23691555#23691555) but it doesnt provide the `getContext()` method. Also you only use the Workspace to get to the KeyBindingDispatcher, so perhaps there is a way to dispatch keys via public api?

I guess even with the warning it's better than the previous state where keybindings didn't work, but it would be nice to avoid these warnings, because internal apis may break in future versions of eclipse (I guess)

**Comment by ddetleffsen** [comment]
I agree using an internal API is in general not a good idea. But we have to dig deep into the internals of eclipse event processing using a class that in my opinion was never intended to be public. To find the proper places for forwarding the KeyEvents, I had to do some reverse engineering. It is possible, that I have overseen a public API, but I doubt. At least I found nothing in the internet. Hopefully if the access to this API is removed one day, the bug in the SWT AWT event processing will be fixed as well ;-)

Adding the bundle `org.eclipse.e4.ui.workbench` to the Manifest is a good idea. But interresting, I had no warning in my environment.

Thank you for merging my changes.

**Pull request merged**
