### PR TITLE
Workaround for issue #524 - Focus not properly returned to SWT parts …

### PR DESCRIPTION
**Pull request by ddetleffsen**
…after hitting any key in a UML diagram.

 - use JApplet instead of Panel to embed AWT Frame.
 - add WindowFocusListener to force the SWT shell to receive the focus.

### CODE REVIEW

**Comment by ddetleffsen** [comment]
Hi Andreas, 
unfortunately this kind of error is hard to test and I do not know how to write a JUnit test for this fix. I am using the patched version in my 2 eclipse installations (oxygen / photon) using Java 8 and 11 under Linux (Ubuntu 16.04). Until know everything works as expected. The SWT parts are processing all key events after leaving the umlet part. I tested entering data in all umlet  elements. Additionally the umlet pop up menus are now closing on leaving the swing context. 
I do not expect any side effects, I am just not able to test my changes on macos or windows, therefore I added the listener only to the gtk version but feel free to add it to all platforms, if you was able to test it, see #524 for a detailled description how to reproduce the problems.
My tests show 2 remaining problems:
1. Hot keys are not working in the umlet part (see #524)
2. Modal dialogs are not longer modal, if switching to the SWT parts.

But that is nothing new and seems to be a general problem in AWT_SWT integrations.

**Comment by afdia** [comment]
Ok thanks I will test a bit more on Windows and merge it if I don't find any problems.
Do you like to fix the typo and remove the `if ("gtk".equals(SWT.getPlatform())) {` part or should I do that after the merge?

**Comment by ddetleffsen** [comment]
typo fixed, if removed and committet

**Comment by ddetleffsen** [comment]
BTW I noticed during my tests, that the maven build fails, if you are using jdk11. A successful build is ony possible using jdk8. (I did not try 9 or 10, because I don't like this versions to much)

**Comment by afdia** [comment]
About switching to Java8: The problem is that this may exclude umlet users which still use Java6+7 (hopefully not many but still possible), therefore I would avoid the upgrade if there is no specific reason for it.
I have already updated some dependencies in 5514cd52436271d92e87dbac56d11f70eb5faa0a (junit because it's just a test dep, gwt in order to possibly get a more optimized javascript build, autocomplete, rsyntaxtextarea and itextpdf because there are several bugreports which are probably related to them and hopefully will be fixed).
If a dependency is known to work without problems, I would not update them at the moment.

I would delay the update to java8 and updating all dependencies for the next major version of umlet (15) which will probably be when we do some major updates.

I will test if I can reproduce the problem with the hidden dialog on Windows, but if everything works I guess I can merge this pull request.

**Comment by afdia** [comment]
Thanks, now it looks good and I will merge this pull request if you would say it's finished.

About Java8: I would suggest everyone to use Java8 instead of 6 or 7, but the question is if we have to force them to even if they have no problems with 6 or 7 (e.g. if  they are using old Eclipse versions or standalone UMLet).
If using Java8 solves problems which only occur in older Java versions, then we can suggest people to update their JRE without influencing other peoples which don't have a problem.

If a new API has been introduced with 7 or 8 which helps us fixing a problem, then I'm all in for updating the min Java version for UMLet. I just don't want to force a higher min Java version if there is no need for it.

**Pull request merged**
